# Generated by Django 3.0.4 on 2020-03-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('follower', models.IntegerField()),
            ],
            options={
                'db_table': 'following',
                'unique_together': {('user_id', 'follower')},
            },
        ),
    ]
