# Generated by Django 3.0.2 on 2020-02-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeposts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
