# Generated by Django 3.0.2 on 2020-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('makeposts', '0003_auto_20200205_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
    ]
