# Generated by Django 3.0.4 on 2020-03-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeposts', '0006_auto_20200306_0404'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
