# Generated by Django 3.0.4 on 2020-03-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeposts', '0007_auto_20200306_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('liked_by', models.IntegerField()),
            ],
            options={
                'db_table': 'likes',
                'unique_together': {('post_id', 'liked_by')},
            },
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
