# Generated by Django 3.0.4 on 2020-03-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeposts', '0008_auto_20200324_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
