# Generated by Django 3.0.4 on 2020-04-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeposts', '0011_auto_20200326_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
